Procedure fst15fnc
close databases

USE \KENSERVE\IDSSYS\st15f.DBF   EXCLUSIVE
go top
if  eof()
APPEND FROM \KENSERVICE\DATA\st15f.DBF
SET SAFETY OFF
COPY STRU TO \KENSERVICE\DATA\st15f DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\st15f.DBF
APPE FROM  \KENSERVE\IDSSYS\st15f.DBF
USE \KENSERVE\IDSSYS\st15f.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\scashrec.dbf   EXCLUSIVE
go top
if  eof()
APPEND FROM \KENSERVICE\DATA\scashrec.DBF
SET SAFETY OFF
COPY STRU TO \KENSERVICE\DATA\scashrec DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\scashrec.DBF
APPE FROM  \KENSERVE\IDSSYS\scashrec.DBF
USE \KENSERVE\IDSSYS\scashrec.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\shiftbk.DBF   EXCLUSIVE
go top
if  eof()
APPEND FROM \KENSERVICE\DATA\shiftbk.DBF
SET SAFETY OFF
COPY STRU TO \KENSERVICE\DATA\shiftbk DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\shiftbk.DBF
APPE FROM  \KENSERVE\IDSSYS\shiftbk.DBF
USE \KENSERVE\IDSSYS\shiftbk.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\dshiftbk.dbf   EXCLUSIVE
go top
if  eof()
APPEND FROM \KENSERVICE\DATA\dshiftbk.DBF
SET SAFETY OFF
COPY STRU TO \KENSERVICE\DATA\dshiftbk DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\dshiftbk.DBF
APPE FROM  \KENSERVE\IDSSYS\dshiftbk.DBF
USE \KENSERVE\IDSSYS\dshiftbk.DBF exclusive
zap
endif
close databases
set safety on