procedure ngfnlstr
close databases
set safety off

USE \KENSERVE\IDSSYS\ngfgnlif.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\ngfgnlif.DBF
COPY STRU TO \KENSERVICE\DATA\ngfgnlif DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\ngfgnlif.DBF
APPE FROM  \KENSERVE\IDSSYS\ngfgnlif.DBF
USE \KENSERVE\IDSSYS\ngfgnlif.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\ngltran.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\ngltran.DBF
COPY STRU TO \KENSERVICE\DATA\ngltran DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\ngltran.DBF
APPE FROM  \KENSERVE\IDSSYS\ngltran.DBF
USE \KENSERVE\IDSSYS\ngltran.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\nglmast.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\nglmast.DBF
COPY STRU TO \KENSERVICE\DATA\nglmast DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\nglmast.DBF
APPE FROM  \KENSERVE\IDSSYS\nglmast.DBF
USE \KENSERVE\IDSSYS\nglmast.DBF exclusive
zap
endif

USE \KENSERVE\IDSSYS\NLBANK.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\NLBANK.DBF
COPY STRU TO \KENSERVICE\DATA\NLBANK DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\NLBANK.DBF
APPE FROM  \KENSERVE\IDSSYS\NLBANK.DBF
USE \KENSERVE\IDSSYS\NLBANK.DBF exclusive
zap
endif

USE \KENSERVE\IDSSYS\NLBANKC.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\NLBANKC.DBF
COPY STRU TO \KENSERVICE\DATA\NLBANKC DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\NLBANKC.DBF
APPE FROM  \KENSERVE\IDSSYS\NLBANKC.DBF
USE \KENSERVE\IDSSYS\NLBANKC.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\NLCASHC.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\NLCASHC.DBF
COPY STRU TO \KENSERVICE\DATA\NLCASHC DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\NLCASHC.DBF
APPE FROM  \KENSERVE\IDSSYS\NLCASHC.DBF
USE \KENSERVE\IDSSYS\NLCASHC.DBF exclusive
zap
endif

USE \KENSERVE\IDSSYS\NLCASH.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\NLCASH.DBF
COPY STRU TO \KENSERVICE\DATA\NLCASH DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\NLCASH.DBF
APPE FROM  \KENSERVE\IDSSYS\NLCASH.DBF
USE \KENSERVE\IDSSYS\NLCASH.DBF exclusive
zap
endif
close databases