Procedure stotank
set safety off
USE \KENSERVE\IDSSYS\STSTO.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\STSTO.DBF
COPY STRU TO \KENSERVICE\DATA\STSTO DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\STSTO.DBF
APPE FROM  \KENSERVE\IDSSYS\STSTO.DBF
USE \KENSERVE\IDSSYS\STSTO.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\STSTOS.DBF  EXCLUSIVE
go top
if eof()
APPEND FROM \KENSERVICE\DATA\STSTOS.DBF
COPY STRU TO \KENSERVICE\DATA\STSTOS DBASE PROD
CLOSE DATABASES
USE \KENSERVICE\DATA\STSTOS.DBF
APPE FROM  \KENSERVE\IDSSYS\STSTOS.DBF
USE \KENSERVE\IDSSYS\STSTOS.DBF exclusive
zap
endif
USE \KENSERVE\IDSSYS\apogrlin.DBF
COPY STRU TO \KENSERVICE\DATA\apogrlin DBASE PROD
COPY STRU TO \KENSERVICE\SYSDATA\DATA\apogrlin DBASE PROD
CLOSE DATABASES
SET SAFETY OFF